// Shared metadata builder for the editorial cluster. Each room in
// La Maison uses this to publish a consistent OpenGraph + Twitter
// card, so link previews on Twitter / Discord / Slack / iMessage
// render the editorial title rather than the default Tickra share.

import type { Metadata } from 'next';
import { SITE_URL } from '@/lib/site-url';
import { isLocale, type Locale } from '@/lib/i18n/config';

export type EditorialMetaInput = {
  /** Page slug relative to the locale prefix, e.g. "lettre". */
  slug: string;
  /** Page title in its primary language. "· Tickra" is appended. */
  title: string;
  /** Short page description, used for OG and Twitter. */
  description: string;
  /** Locale to anchor the canonical URL. Defaults to fr. */
  locale?: 'fr' | 'en';
  /** Optional eyebrow rendered on the /api/og share card mono caption.
   * Matches the pageMeta API for cross-helper consistency. */
  ogEyebrow?: string;
  /**
   * When true, the room is a candor-stub: published but not finished.
   * Emits `robots: noindex, follow` so crawlers don't dilute the catalog
   * with hollow pages. The room stays linkable from /maison.
   */
  draft?: boolean;
};

export function editorialMeta({
  slug,
  title,
  description,
  locale = 'fr',
  ogEyebrow,
  draft = false,
}: EditorialMetaInput): Metadata {
  const path = slug.startsWith('/') ? slug : `/${slug}`;
  const url = `${SITE_URL}/${locale}${path}`;
  // hreflang alternates: tell search engines that fr and en are
  // translations of the same page, plus an x-default fallback.
  const languages = {
    'fr-FR': `${SITE_URL}/fr${path}`,
    'en-GB': `${SITE_URL}/en${path}`,
    'x-default': `${SITE_URL}/fr${path}`,
  };
  // Editorial share card — ivory paper, italic title, mono captions.
  // Generated by /api/og on the first request per (title, eyebrow, locale)
  // tuple, then served from Vercel's edge cache for 24h.
  const ogParams = new URLSearchParams({
    title,
    locale,
  });
  if (ogEyebrow) ogParams.set('eyebrow', ogEyebrow);
  const ogImage = `${SITE_URL}/api/og?${ogParams.toString()}`;
  return {
    title: `${title} · Tickra`,
    description,
    ...(draft && { robots: { index: false, follow: true } }),
    alternates: {
      canonical: url,
      languages,
    },
    openGraph: {
      title,
      description,
      type: 'article',
      url,
      siteName: 'Tickra',
      locale: locale === 'fr' ? 'fr_FR' : 'en_GB',
      alternateLocale: locale === 'fr' ? ['en_GB'] : ['fr_FR'],
      images: [
        {
          url: ogImage,
          width: 1200,
          height: 630,
          alt: title,
        },
      ],
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      site: '@tickra',
      creator: '@tickra',
      images: [ogImage],
    },
  };
}

/**
 * Locale-aware editorial metadata generator. Returns a Next.js
 * generateMetadata function that picks the right title/description
 * per locale and emits canonical + hreflang from editorialMeta.
 *
 * Replaces the broken `export const metadata = editorialMeta(...)`
 * pattern, which ran once at build time with the default 'fr'
 * locale — so /en/<page> canonicalised back to /fr/<page> and
 * shipped a French title in <head> over English content.
 */
type Bi = { fr: string; en: string };

export function editorialPageMeta(input: {
  slug: string;
  title: Bi;
  description: Bi;
  ogEyebrow?: Bi;
  draft?: boolean;
}) {
  return async function generateMetadata({
    params,
  }: {
    params: { locale: string };
  }): Promise<Metadata> {
    if (!isLocale(params.locale)) return {};
    const locale: Locale = params.locale;
    return editorialMeta({
      slug: input.slug,
      title: input.title[locale],
      description: input.description[locale],
      locale,
      ogEyebrow: input.ogEyebrow?.[locale],
      draft: input.draft,
    });
  };
}
