// Shared metadata builder for the editorial cluster. Each room in
// La Maison uses this to publish a consistent OpenGraph + Twitter
// card, so link previews on Twitter / Discord / Slack / iMessage
// render the editorial title rather than the default nkNOWTrade share.

import type { Metadata } from 'next';
import { SITE_URL } from '@/lib/site-url';

/** A string used for both locales, or one string per locale. */
type Localised = string | { fr: string; en: string };

const pick = (value: Localised, locale: 'fr' | 'en'): string =>
  typeof value === 'string' ? value : value[locale];

export type EditorialMetaInput = {
  /** Page slug relative to the locale prefix, e.g. "lettre". */
  slug: string;
  /** Page title. "· nkNOWTrade" is appended. */
  title: Localised;
  /** Short page description, used for OG and Twitter. */
  description: Localised;
  /**
   * Locale of the page being rendered.
   *
   * This MUST come from the route params. Every caller used to leave it out
   * and assign the result to `export const metadata` — a module-level constant
   * evaluated once — so all sixteen editorial rooms served French titles and a
   * canonical pointing at `/fr/<slug>` on their `/en/` URLs too. The English
   * versions were therefore unindexable, and English readers got French
   * browser tabs on rooms linked straight from the navbar. Callers now use
   * `generateMetadata({ params })` and pass the real locale.
   */
  locale?: 'fr' | 'en';
  /** Optional editorial eyebrow shown on the share-card mono caption. */
  eyebrow?: Localised;
};

export function editorialMeta({
  slug,
  title: titleInput,
  description: descriptionInput,
  locale = 'fr',
  eyebrow: eyebrowInput,
}: EditorialMetaInput): Metadata {
  const title = pick(titleInput, locale);
  const description = pick(descriptionInput, locale);
  const eyebrow = eyebrowInput ? pick(eyebrowInput, locale) : undefined;
  const path = slug.startsWith('/') ? slug : `/${slug}`;
  const url = `${SITE_URL}/${locale}${path}`;
  // hreflang alternates: tell search engines that fr and en are
  // translations of the same page, plus an x-default fallback.
  const languages = {
    'fr-FR': `${SITE_URL}/fr${path}`,
    'en-GB': `${SITE_URL}/en${path}`,
    'x-default': `${SITE_URL}/fr${path}`,
  };
  // Editorial share card — ivory paper, italic title, mono captions.
  // Generated by /api/og at request time so every page gets a unique
  // preview without a static asset per route.
  const ogParams = new URLSearchParams({
    title,
    locale,
  });
  if (eyebrow) ogParams.set('eyebrow', eyebrow);
  const ogImage = `${SITE_URL}/api/og?${ogParams.toString()}`;
  return {
    // NOT `${title} · nkNOWTrade`. The root layout sets
    // `title: { template: '%s · nkNOWTrade' }`, and Next applies that template
    // to any plain-string title a child page returns — so appending the brand
    // here produced "The Criée · nkNOWTrade · nkNOWTrade" in the browser tab
    // and in search results, on all sixteen editorial rooms. Caught on a
    // deployed preview, not by reading: the template lives in another file.
    // og:title below takes no template, so it keeps the bare title.
    title,
    description,
    alternates: {
      canonical: url,
      languages,
    },
    openGraph: {
      title,
      description,
      type: 'article',
      url,
      siteName: 'nkNOWTrade',
      locale: locale === 'fr' ? 'fr_FR' : 'en_GB',
      alternateLocale: locale === 'fr' ? ['en_GB'] : ['fr_FR'],
      images: [
        {
          url: ogImage,
          width: 1200,
          height: 630,
          alt: title,
        },
      ],
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [ogImage],
    },
  };
}
