// Shared metadata builder for the editorial cluster. Each room in
// La Maison uses this to publish a consistent OpenGraph + Twitter
// card, so link previews on Twitter / Discord / Slack / iMessage
// render the editorial title rather than the default kNOWTrade share.

import type { Metadata } from 'next';
import { SITE_URL } from '@/lib/site-url';

export type EditorialMetaInput = {
  /** Page slug relative to the locale prefix, e.g. "lettre". */
  slug: string;
  /** Page title in its primary language. "· kNOWTrade" is appended. */
  title: string;
  /** Short page description, used for OG and Twitter. */
  description: string;
  /** Locale to anchor the canonical URL. Defaults to fr. */
  locale?: 'fr' | 'en';
  /** Optional editorial eyebrow shown on the share-card mono caption. */
  eyebrow?: string;
};

export function editorialMeta({
  slug,
  title,
  description,
  locale = 'fr',
  eyebrow,
}: EditorialMetaInput): Metadata {
  const path = slug.startsWith('/') ? slug : `/${slug}`;
  const url = `${SITE_URL}/${locale}${path}`;
  // hreflang alternates: tell search engines that fr and en are
  // translations of the same page, plus an x-default fallback.
  const languages = {
    'fr-FR': `${SITE_URL}/fr${path}`,
    'en-GB': `${SITE_URL}/en${path}`,
    'x-default': `${SITE_URL}/fr${path}`,
  };
  // Editorial share card — ivory paper, italic title, mono captions.
  // Generated by /api/og at request time so every page gets a unique
  // preview without a static asset per route.
  const ogParams = new URLSearchParams({
    title,
    locale,
  });
  if (eyebrow) ogParams.set('eyebrow', eyebrow);
  const ogImage = `${SITE_URL}/api/og?${ogParams.toString()}`;
  return {
    title: `${title} · kNOWTrade`,
    description,
    alternates: {
      canonical: url,
      languages,
    },
    openGraph: {
      title,
      description,
      type: 'article',
      url,
      siteName: 'kNOWTrade',
      locale: locale === 'fr' ? 'fr_FR' : 'en_GB',
      alternateLocale: locale === 'fr' ? ['en_GB'] : ['fr_FR'],
      images: [
        {
          url: ogImage,
          width: 1200,
          height: 630,
          alt: title,
        },
      ],
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [ogImage],
    },
  };
}
